export const ALL_LISTS_REQUEST = "ALL_LISTS_REQUEST";
export const ALL_LISTS_SUCCESS = "ALL_LISTS_SUCCESS";
export const ALL_LISTS_FAIL = "ALL_LISTS_FAIL";

export const INDIVIDUAL_LIST_REQUEST = "INDIVIDUAL_LIST_REQUEST";
export const INDIVIDUAL_LIST_SUCCESS = "INDIVIDUAL_LIST_SUCCESS";
export const INDIVIDUAL_LIST_FAIL = "INDIVIDUAL_LIST_FAIL";
export const INDIVIDUAL_LIST_RESET = "INDIVIDUAL_LIST_RESET";

export const CREATE_LIST_REQUEST = "CREATE_LIST_REQUEST";
export const CREATE_LIST_SUCCESS = "CREATE_LIST_SUCCESS";
export const CREATE_LIST_FAIL = "CREATE_LIST_FAIL";

export const DELETE_LIST_REQUEST = "DELETE_LIST_REQUEST";
export const DELETE_LIST_SUCCESS = "DELETE_LIST_SUCCESS";
export const DELETE_LIST_FAIL = "DELETE_LIST_FAIL";

export const CREATE_LIST_ITEM_REQUEST = "CREATE_LIST_ITEM_REQUEST";
export const CREATE_LIST_ITEM_SUCCESS = "CREATE_LIST_ITEM_SUCCESS";
export const CREATE_LIST_ITEM_FAIL = "CREATE_LIST_ITEM_FAIL";

export const DELETE_LIST_ITEM_REQUEST = "DELETE_LIST_ITEM_REQUEST";
export const DELETE_LIST_ITEM_SUCCESS = "DELETE_LIST_ITEM_SUCCESS";
export const DELETE_LIST_ITEM_FAIL = "DELETE_LIST_ITEM_FAIL";

export const GET_LIST_ITEM_REQUEST = "GET_LIST_ITEM_REQUEST";
export const GET_LIST_ITEM_SUCCESS = "GET_LIST_ITEM_SUCCESS";
export const GET_LIST_ITEM_FAIL = "GET_LIST_ITEM_FAIL";
export const GET_LIST_ITEM_RESET = "GET_LIST_ITEM_RESET";

export const UPDATE_LIST_ITEM_REQUEST = "UPDATE_LIST_ITEM_REQUEST";
export const UPDATE_LIST_ITEM_SUCCESS = "UPDATE_LIST_ITEM_SUCCESS";
export const UPDATE_LIST_ITEM_FAIL = "UPDATE_LIST_ITEM_FAIL";
export const UPDATE_LIST_ITEM_RESET = "UPDATE_LIST_ITEM_RESET";
