export const ALL_LISTS_REQUEST = "ALL_LISTS_REQUEST";
export const ALL_LISTS_SUCCESS = "ALL_LISTS_SUCCESS";
export const ALL_LISTS_FAIL = "ALL_LISTS_FAIL";

export const INDIVIDUAL_LIST_REQUEST = "INDIVIDUAL_LIST_REQUEST";
export const INDIVIDUAL_LIST_SUCCESS = "INDIVIDUAL_LIST_SUCCESS";
export const INDIVIDUAL_LIST_FAIL = "INDIVIDUAL_LIST_FAIL";
